-- 上海如静知华信息科技有限公司 https://www.zhuatech.cn/
-- 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
CREATE DATABASE IF NOT EXISTS zhuatech_ev_charge DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE zhuatech_ev_charge;

CREATE TABLE station (id VARCHAR(32) PRIMARY KEY, code VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(128) NOT NULL, address VARCHAR(255) NOT NULL, latitude DECIMAL(10,7), longitude DECIMAL(10,7), business_hours VARCHAR(32), parking_free_minutes INT NOT NULL DEFAULT 0, status VARCHAR(24) NOT NULL, created_at DATETIME(3) NOT NULL);
CREATE TABLE tariff (id VARCHAR(32) PRIMARY KEY, name VARCHAR(128) NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'CNY', periods JSON NOT NULL, created_at DATETIME(3) NOT NULL);
CREATE TABLE connector (id VARCHAR(32) PRIMARY KEY, station_id VARCHAR(32) NOT NULL, tariff_id VARCHAR(32) NOT NULL, code VARCHAR(64) NOT NULL UNIQUE, protocol VARCHAR(32) NOT NULL, rated_power_kw DECIMAL(10,2) NOT NULL, status VARCHAR(24) NOT NULL, meter_kwh DECIMAL(16,4) NOT NULL DEFAULT 0, last_heartbeat_at DATETIME(3), version BIGINT NOT NULL DEFAULT 0, created_at DATETIME(3) NOT NULL, CONSTRAINT fk_connector_station FOREIGN KEY (station_id) REFERENCES station(id), CONSTRAINT fk_connector_tariff FOREIGN KEY (tariff_id) REFERENCES tariff(id));
CREATE TABLE customer (id VARCHAR(32) PRIMARY KEY, name VARCHAR(64) NOT NULL, mobile VARCHAR(32) NOT NULL UNIQUE, balance DECIMAL(16,2) NOT NULL DEFAULT 0, status VARCHAR(24) NOT NULL, created_at DATETIME(3) NOT NULL);
CREATE TABLE reservation (id VARCHAR(32) PRIMARY KEY, connector_id VARCHAR(32) NOT NULL, customer_id VARCHAR(32) NOT NULL, status VARCHAR(24) NOT NULL, expires_at DATETIME(3) NOT NULL, created_at DATETIME(3) NOT NULL, INDEX idx_reservation_connector_status(connector_id,status));
CREATE TABLE charge_session (id VARCHAR(32) PRIMARY KEY, connector_id VARCHAR(32) NOT NULL, station_id VARCHAR(32) NOT NULL, customer_id VARCHAR(32) NOT NULL, status VARCHAR(24) NOT NULL, start_meter_kwh DECIMAL(16,4) NOT NULL, last_meter_kwh DECIMAL(16,4) NOT NULL, energy_kwh DECIMAL(16,4) NOT NULL, energy_amount DECIMAL(16,2) NOT NULL, service_amount DECIMAL(16,2) NOT NULL, total_amount DECIMAL(16,2) NOT NULL, outstanding_amount DECIMAL(16,2), started_at DATETIME(3) NOT NULL, stopped_at DATETIME(3), INDEX idx_session_connector_status(connector_id,status));
CREATE TABLE wallet_ledger (id BIGINT PRIMARY KEY AUTO_INCREMENT, customer_id VARCHAR(32) NOT NULL, session_id VARCHAR(32), entry_type VARCHAR(24) NOT NULL, amount DECIMAL(16,2) NOT NULL, balance_after DECIMAL(16,2) NOT NULL, created_at DATETIME(3) NOT NULL, INDEX idx_ledger_customer(customer_id,created_at));
CREATE TABLE work_order (id VARCHAR(32) PRIMARY KEY, connector_id VARCHAR(32) NOT NULL, station_id VARCHAR(32) NOT NULL, severity VARCHAR(16) NOT NULL, fault_code VARCHAR(64) NOT NULL, description VARCHAR(512) NOT NULL, status VARCHAR(24) NOT NULL, assignee VARCHAR(64), resolution VARCHAR(512), created_at DATETIME(3) NOT NULL, closed_at DATETIME(3));
CREATE TABLE audit_event (id VARCHAR(32) PRIMARY KEY, actor VARCHAR(64) NOT NULL, action VARCHAR(64) NOT NULL, resource_id VARCHAR(64) NOT NULL, detail JSON, occurred_at DATETIME(3) NOT NULL, INDEX idx_audit_resource(resource_id,occurred_at));
